# Generated by Django 4.2.4 on 2023-09-09 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualifications',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
